CREATE SCHEMA payment AUTHORIZATION sepa_migration;

GRANT USAGE ON SCHEMA payment TO sepa_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA payment TO sepa_app;
ALTER DEFAULT PRIVILEGES FOR ROLE sepa_migration IN SCHEMA payment
    GRANT SELECT, INSERT, UPDATE ON TABLES TO sepa_app;
